/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { AccountRatedTvEpisodes200ResultsItem } from "./accountRatedTvEpisodes200ResultsItem";

export type AccountRatedTvEpisodes200 = {
  page?: number;
  results?: AccountRatedTvEpisodes200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
