/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type AccountRatedTvSortBy = (typeof AccountRatedTvSortBy)[keyof typeof AccountRatedTvSortBy];

export const AccountRatedTvSortBy = {
  created_atasc: "created_at.asc",
  created_atdesc: "created_at.desc",
} as const;
