/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { AccountDetails200AvatarGravatar } from "./accountDetails200AvatarGravatar";
import type { AccountDetails200AvatarTmdb } from "./accountDetails200AvatarTmdb";

export type AccountDetails200Avatar = {
  gravatar?: AccountDetails200AvatarGravatar;
  tmdb?: AccountDetails200AvatarTmdb;
};
