/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type AccountGetFavoritesSortBy =
  (typeof AccountGetFavoritesSortBy)[keyof typeof AccountGetFavoritesSortBy];

export const AccountGetFavoritesSortBy = {
  created_atasc: "created_at.asc",
  created_atdesc: "created_at.desc",
} as const;
