/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { AccountWatchlistTvSortBy } from "./accountWatchlistTvSortBy";

export type AccountWatchlistTvParams = {
  language?: string;
  page?: number;
  session_id?: string;
  sort_by?: AccountWatchlistTvSortBy;
};
