/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { AccountRatedMoviesSortBy } from "./accountRatedMoviesSortBy";

export type AccountRatedMoviesParams = {
  language?: string;
  page?: number;
  session_id?: string;
  sort_by?: AccountRatedMoviesSortBy;
};
