/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { AccountWatchlistMovies200ResultsItem } from "./accountWatchlistMovies200ResultsItem";

export type AccountWatchlistMovies200 = {
  page?: number;
  results?: AccountWatchlistMovies200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
