/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { AlternativeNamesCopy200LogosItem } from "./alternativeNamesCopy200LogosItem";

export type AlternativeNamesCopy200 = {
  id?: number;
  logos?: AlternativeNamesCopy200LogosItem[];
};
