/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type AuthenticationCreateGuestSession200 = {
  success?: boolean;
  guest_session_id?: string;
  expires_at?: string;
};
