/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type AuthenticationCreateSessionFromV4Token200 = {
  success?: boolean;
  session_id?: string;
};
