/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type AuthenticationCreateRequestToken200 = {
  success?: boolean;
  expires_at?: string;
  request_token?: string;
};
