/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { CertificationMovieList200Certifications } from "./certificationMovieList200Certifications";

export type CertificationMovieList200 = {
  certifications?: CertificationMovieList200Certifications;
};
