/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type CertificationsTvList200CertificationsBGItem = {
  certification?: string;
  meaning?: string;
  order?: number;
};
