/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { CertificationsTvList200Certifications } from "./certificationsTvList200Certifications";

export type CertificationsTvList200 = {
  certifications?: CertificationsTvList200Certifications;
};
