/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { ChangesPeopleList200ResultsItem } from "./changesPeopleList200ResultsItem";

export type ChangesPeopleList200 = {
  results?: ChangesPeopleList200ResultsItem[];
  page?: number;
  total_pages?: number;
  total_results?: number;
};
