/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { CollectionTranslations200TranslationsItem } from "./collectionTranslations200TranslationsItem";

export type CollectionTranslations200 = {
  id?: number;
  translations?: CollectionTranslations200TranslationsItem[];
};
