/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type CollectionTranslations200TranslationsItemData = {
  title?: string;
  overview?: string;
  homepage?: string;
};
