/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type CompanyDetails200 = {
  description?: string;
  headquarters?: string;
  homepage?: string;
  id?: number;
  logo_path?: string;
  name?: string;
  origin_country?: string;
  parent_company?: unknown;
};
