/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { CompanyAlternativeNames200ResultsItem } from "./companyAlternativeNames200ResultsItem";

export type CompanyAlternativeNames200 = {
  id?: number;
  results?: CompanyAlternativeNames200ResultsItem[];
};
