/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { CompanyImages200LogosItem } from "./companyImages200LogosItem";

export type CompanyImages200 = {
  id?: number;
  logos?: CompanyImages200LogosItem[];
};
