/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type ConfigurationLanguages200Item = {
  iso_639_1?: string;
  english_name?: string;
  name?: string;
};
