/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { ConfigurationDetails200Images } from "./configurationDetails200Images";

export type ConfigurationDetails200 = {
  images?: ConfigurationDetails200Images;
  change_keys?: string[];
};
