/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { DetailsCopy200ResultsItem } from "./detailsCopy200ResultsItem";

export type DetailsCopy200 = {
  id?: number;
  results?: DetailsCopy200ResultsItem[];
};
