/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type DiscoverTvSortBy = (typeof DiscoverTvSortBy)[keyof typeof DiscoverTvSortBy];

export const DiscoverTvSortBy = {
  first_air_dateasc: "first_air_date.asc",
  first_air_datedesc: "first_air_date.desc",
  nameasc: "name.asc",
  namedesc: "name.desc",
  original_nameasc: "original_name.asc",
  original_namedesc: "original_name.desc",
  popularityasc: "popularity.asc",
  popularitydesc: "popularity.desc",
  vote_averageasc: "vote_average.asc",
  vote_averagedesc: "vote_average.desc",
  vote_countasc: "vote_count.asc",
  vote_countdesc: "vote_count.desc",
} as const;
