/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { DiscoverMovie200ResultsItem } from "./discoverMovie200ResultsItem";

export type DiscoverMovie200 = {
  page?: number;
  results?: DiscoverMovie200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
