/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { FindByIdExternalSource } from "./findByIdExternalSource";

export type FindByIdParams = {
  external_source: FindByIdExternalSource;
  language?: string;
};
