/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { GenreMovieList200GenresItem } from "./genreMovieList200GenresItem";

export type GenreMovieList200 = {
  genres?: GenreMovieList200GenresItem[];
};
