/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { GenreTvList200GenresItem } from "./genreTvList200GenresItem";

export type GenreTvList200 = {
  genres?: GenreTvList200GenresItem[];
};
