/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { GuestSessionRatedTvSortBy } from "./guestSessionRatedTvSortBy";

export type GuestSessionRatedTvParams = {
  language?: string;
  page?: number;
  sort_by?: GuestSessionRatedTvSortBy;
};
