/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { GuestSessionRatedTvEpisodesSortBy } from "./guestSessionRatedTvEpisodesSortBy";

export type GuestSessionRatedTvEpisodesParams = {
  language?: string;
  page?: number;
  sort_by?: GuestSessionRatedTvEpisodesSortBy;
};
