/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { GuestSessionRatedMovies200ResultsItem } from "./guestSessionRatedMovies200ResultsItem";

export type GuestSessionRatedMovies200 = {
  page?: number;
  results?: GuestSessionRatedMovies200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
