/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { GuestSessionRatedTv200ResultsItem } from "./guestSessionRatedTv200ResultsItem";

export type GuestSessionRatedTv200 = {
  page?: number;
  results?: GuestSessionRatedTv200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
