/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { GuestSessionRatedMoviesSortBy } from "./guestSessionRatedMoviesSortBy";

export type GuestSessionRatedMoviesParams = {
  language?: string;
  page?: number;
  sort_by?: GuestSessionRatedMoviesSortBy;
};
