/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type GuestSessionRatedMoviesSortBy =
  (typeof GuestSessionRatedMoviesSortBy)[keyof typeof GuestSessionRatedMoviesSortBy];

export const GuestSessionRatedMoviesSortBy = {
  created_atasc: "created_at.asc",
  created_atdesc: "created_at.desc",
} as const;
