/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type KeywordMoviesParams = {
  include_adult?: boolean;
  language?: string;
  page?: number;
};
