/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type ListCreate200 = {
  status_message?: string;
  success?: boolean;
  status_code?: number;
  list_id?: number;
};
