/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type MovieDetailsParams = {
  /**
   * comma separated list of endpoints within this namespace, 20 items max
   */
  append_to_response?: string;
  language?: string;
};
