/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type MovieDetails200BelongsToCollection = {
  id?: number;
  name?: string;
  poster_path?: string;
  backdrop_path?: string;
};
