/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieAlternativeTitles200TitlesItem } from "./movieAlternativeTitles200TitlesItem";

export type MovieAlternativeTitles200 = {
  id?: number;
  titles?: MovieAlternativeTitles200TitlesItem[];
};
