/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsCRFlatrateItem } from "./movieWatchProviders200ResultsCRFlatrateItem";

export type MovieWatchProviders200ResultsCR = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsCRFlatrateItem[];
};
