/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type MovieReleaseDates200ResultsItemReleaseDatesItem = {
  certification?: string;
  descriptors?: unknown[];
  iso_639_1?: string;
  note?: string;
  release_date?: string;
  type?: number;
};
