/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsJOBuyItem } from "./movieWatchProviders200ResultsJOBuyItem";
import type { MovieWatchProviders200ResultsJOFlatrateItem } from "./movieWatchProviders200ResultsJOFlatrateItem";

export type MovieWatchProviders200ResultsJO = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsJOFlatrateItem[];
  buy?: MovieWatchProviders200ResultsJOBuyItem[];
};
