/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsKWBuyItem } from "./movieWatchProviders200ResultsKWBuyItem";
import type { MovieWatchProviders200ResultsKWFlatrateItem } from "./movieWatchProviders200ResultsKWFlatrateItem";

export type MovieWatchProviders200ResultsKW = {
  link?: string;
  buy?: MovieWatchProviders200ResultsKWBuyItem[];
  flatrate?: MovieWatchProviders200ResultsKWFlatrateItem[];
};
