/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsSGFlatrateItem } from "./movieWatchProviders200ResultsSGFlatrateItem";

export type MovieWatchProviders200ResultsSG = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsSGFlatrateItem[];
};
