/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsJMFlatrateItem } from "./movieWatchProviders200ResultsJMFlatrateItem";

export type MovieWatchProviders200ResultsJM = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsJMFlatrateItem[];
};
