/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsNZBuyItem } from "./movieWatchProviders200ResultsNZBuyItem";
import type { MovieWatchProviders200ResultsNZFlatrateItem } from "./movieWatchProviders200ResultsNZFlatrateItem";

export type MovieWatchProviders200ResultsNZ = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsNZFlatrateItem[];
  buy?: MovieWatchProviders200ResultsNZBuyItem[];
};
