/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsGIFlatrateItem } from "./movieWatchProviders200ResultsGIFlatrateItem";

export type MovieWatchProviders200ResultsGI = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsGIFlatrateItem[];
};
