/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsROFlatrateItem } from "./movieWatchProviders200ResultsROFlatrateItem";

export type MovieWatchProviders200ResultsRO = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsROFlatrateItem[];
};
