/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsMKBuyItem } from "./movieWatchProviders200ResultsMKBuyItem";
import type { MovieWatchProviders200ResultsMKFlatrateItem } from "./movieWatchProviders200ResultsMKFlatrateItem";

export type MovieWatchProviders200ResultsMK = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsMKFlatrateItem[];
  buy?: MovieWatchProviders200ResultsMKBuyItem[];
};
