/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieVideos200ResultsItem } from "./movieVideos200ResultsItem";

export type MovieVideos200 = {
  id?: number;
  results?: MovieVideos200ResultsItem[];
};
