/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsTWFlatrateItem } from "./movieWatchProviders200ResultsTWFlatrateItem";

export type MovieWatchProviders200ResultsTW = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsTWFlatrateItem[];
};
