/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200Results } from "./movieWatchProviders200Results";

export type MovieWatchProviders200 = {
  id?: number;
  results?: MovieWatchProviders200Results;
};
