/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsKRBuyItem } from "./movieWatchProviders200ResultsKRBuyItem";
import type { MovieWatchProviders200ResultsKRFlatrateItem } from "./movieWatchProviders200ResultsKRFlatrateItem";

export type MovieWatchProviders200ResultsKR = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsKRFlatrateItem[];
  buy?: MovieWatchProviders200ResultsKRBuyItem[];
};
