/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsSVFlatrateItem } from "./movieWatchProviders200ResultsSVFlatrateItem";

export type MovieWatchProviders200ResultsSV = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsSVFlatrateItem[];
};
