/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsTRBuyItem } from "./movieWatchProviders200ResultsTRBuyItem";
import type { MovieWatchProviders200ResultsTRFlatrateItem } from "./movieWatchProviders200ResultsTRFlatrateItem";
import type { MovieWatchProviders200ResultsTRRentItem } from "./movieWatchProviders200ResultsTRRentItem";

export type MovieWatchProviders200ResultsTR = {
  link?: string;
  rent?: MovieWatchProviders200ResultsTRRentItem[];
  flatrate?: MovieWatchProviders200ResultsTRFlatrateItem[];
  buy?: MovieWatchProviders200ResultsTRBuyItem[];
};
