/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsDOFlatrateItem } from "./movieWatchProviders200ResultsDOFlatrateItem";

export type MovieWatchProviders200ResultsDO = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsDOFlatrateItem[];
};
