/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsMYFlatrateItem } from "./movieWatchProviders200ResultsMYFlatrateItem";

export type MovieWatchProviders200ResultsMY = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsMYFlatrateItem[];
};
