/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsHNFlatrateItem } from "./movieWatchProviders200ResultsHNFlatrateItem";

export type MovieWatchProviders200ResultsHN = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsHNFlatrateItem[];
};
