/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsGFFlatrateItem } from "./movieWatchProviders200ResultsGFFlatrateItem";

export type MovieWatchProviders200ResultsGF = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsGFFlatrateItem[];
};
