/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type MovieNowPlayingListParams = {
  language?: string;
  page?: number;
  /**
   * ISO-3166-1 code
   */
  region?: string;
};
