/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsLIFlatrateItem } from "./movieWatchProviders200ResultsLIFlatrateItem";

export type MovieWatchProviders200ResultsLI = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsLIFlatrateItem[];
};
