/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsBBFlatrateItem } from "./movieWatchProviders200ResultsBBFlatrateItem";

export type MovieWatchProviders200ResultsBB = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsBBFlatrateItem[];
};
