/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsBOFlatrateItem } from "./movieWatchProviders200ResultsBOFlatrateItem";

export type MovieWatchProviders200ResultsBO = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsBOFlatrateItem[];
};
