/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsRUBuyItem } from "./movieWatchProviders200ResultsRUBuyItem";
import type { MovieWatchProviders200ResultsRUFlatrateItem } from "./movieWatchProviders200ResultsRUFlatrateItem";
import type { MovieWatchProviders200ResultsRURentItem } from "./movieWatchProviders200ResultsRURentItem";

export type MovieWatchProviders200ResultsRU = {
  link?: string;
  rent?: MovieWatchProviders200ResultsRURentItem[];
  buy?: MovieWatchProviders200ResultsRUBuyItem[];
  flatrate?: MovieWatchProviders200ResultsRUFlatrateItem[];
};
