/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsTTFlatrateItem } from "./movieWatchProviders200ResultsTTFlatrateItem";

export type MovieWatchProviders200ResultsTT = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsTTFlatrateItem[];
};
