/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsNLBuyItem } from "./movieWatchProviders200ResultsNLBuyItem";
import type { MovieWatchProviders200ResultsNLFlatrateItem } from "./movieWatchProviders200ResultsNLFlatrateItem";
import type { MovieWatchProviders200ResultsNLRentItem } from "./movieWatchProviders200ResultsNLRentItem";

export type MovieWatchProviders200ResultsNL = {
  link?: string;
  buy?: MovieWatchProviders200ResultsNLBuyItem[];
  rent?: MovieWatchProviders200ResultsNLRentItem[];
  flatrate?: MovieWatchProviders200ResultsNLFlatrateItem[];
};
