/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type MovieAlternativeTitlesParams = {
  /**
   * specify a ISO-3166-1 value to filter the results
   */
  country?: string;
};
