/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type MovieReviews200ResultsItemAuthorDetails = {
  name?: string;
  username?: string;
  avatar_path?: string;
  rating?: unknown;
};
