/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieTopRatedList200ResultsItem } from "./movieTopRatedList200ResultsItem";

export type MovieTopRatedList200 = {
  page?: number;
  results?: MovieTopRatedList200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
