/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsUGBuyItem } from "./movieWatchProviders200ResultsUGBuyItem";
import type { MovieWatchProviders200ResultsUGRentItem } from "./movieWatchProviders200ResultsUGRentItem";

export type MovieWatchProviders200ResultsUG = {
  link?: string;
  rent?: MovieWatchProviders200ResultsUGRentItem[];
  buy?: MovieWatchProviders200ResultsUGBuyItem[];
};
