/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsCVBuyItem } from "./movieWatchProviders200ResultsCVBuyItem";
import type { MovieWatchProviders200ResultsCVRentItem } from "./movieWatchProviders200ResultsCVRentItem";

export type MovieWatchProviders200ResultsCV = {
  link?: string;
  buy?: MovieWatchProviders200ResultsCVBuyItem[];
  rent?: MovieWatchProviders200ResultsCVRentItem[];
};
