/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsIEBuyItem } from "./movieWatchProviders200ResultsIEBuyItem";
import type { MovieWatchProviders200ResultsIEFlatrateItem } from "./movieWatchProviders200ResultsIEFlatrateItem";
import type { MovieWatchProviders200ResultsIERentItem } from "./movieWatchProviders200ResultsIERentItem";

export type MovieWatchProviders200ResultsIE = {
  link?: string;
  rent?: MovieWatchProviders200ResultsIERentItem[];
  flatrate?: MovieWatchProviders200ResultsIEFlatrateItem[];
  buy?: MovieWatchProviders200ResultsIEBuyItem[];
};
