/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsPSFlatrateItem } from "./movieWatchProviders200ResultsPSFlatrateItem";

export type MovieWatchProviders200ResultsPS = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsPSFlatrateItem[];
};
