/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsQABuyItem } from "./movieWatchProviders200ResultsQABuyItem";
import type { MovieWatchProviders200ResultsQAFlatrateItem } from "./movieWatchProviders200ResultsQAFlatrateItem";

export type MovieWatchProviders200ResultsQA = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsQAFlatrateItem[];
  buy?: MovieWatchProviders200ResultsQABuyItem[];
};
