/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsBHBuyItem } from "./movieWatchProviders200ResultsBHBuyItem";

export type MovieWatchProviders200ResultsBH = {
  link?: string;
  buy?: MovieWatchProviders200ResultsBHBuyItem[];
};
