/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsUYFlatrateItem } from "./movieWatchProviders200ResultsUYFlatrateItem";

export type MovieWatchProviders200ResultsUY = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsUYFlatrateItem[];
};
