/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsPAFlatrateItem } from "./movieWatchProviders200ResultsPAFlatrateItem";

export type MovieWatchProviders200ResultsPA = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsPAFlatrateItem[];
};
