/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsLBBuyItem } from "./movieWatchProviders200ResultsLBBuyItem";
import type { MovieWatchProviders200ResultsLBFlatrateItem } from "./movieWatchProviders200ResultsLBFlatrateItem";

export type MovieWatchProviders200ResultsLB = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsLBFlatrateItem[];
  buy?: MovieWatchProviders200ResultsLBBuyItem[];
};
