/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieChanges200ChangesItem } from "./movieChanges200ChangesItem";

export type MovieChanges200 = {
  changes?: MovieChanges200ChangesItem[];
};
