/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsMXFlatrateItem } from "./movieWatchProviders200ResultsMXFlatrateItem";

export type MovieWatchProviders200ResultsMX = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsMXFlatrateItem[];
};
