/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type MovieDetails200ProductionCountriesItem = {
  iso_3166_1?: string;
  name?: string;
};
