/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsALBuyItem } from "./movieWatchProviders200ResultsALBuyItem";

export type MovieWatchProviders200ResultsAL = {
  link?: string;
  buy?: MovieWatchProviders200ResultsALBuyItem[];
};
