/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsHRAdsItem } from "./movieWatchProviders200ResultsHRAdsItem";
import type { MovieWatchProviders200ResultsHRBuyItem } from "./movieWatchProviders200ResultsHRBuyItem";
import type { MovieWatchProviders200ResultsHRFlatrateItem } from "./movieWatchProviders200ResultsHRFlatrateItem";

export type MovieWatchProviders200ResultsHR = {
  link?: string;
  buy?: MovieWatchProviders200ResultsHRBuyItem[];
  ads?: MovieWatchProviders200ResultsHRAdsItem[];
  flatrate?: MovieWatchProviders200ResultsHRFlatrateItem[];
};
