/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsPYFlatrateItem } from "./movieWatchProviders200ResultsPYFlatrateItem";

export type MovieWatchProviders200ResultsPY = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsPYFlatrateItem[];
};
