/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsZABuyItem } from "./movieWatchProviders200ResultsZABuyItem";
import type { MovieWatchProviders200ResultsZAFlatrateItem } from "./movieWatchProviders200ResultsZAFlatrateItem";
import type { MovieWatchProviders200ResultsZARentItem } from "./movieWatchProviders200ResultsZARentItem";

export type MovieWatchProviders200ResultsZA = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsZAFlatrateItem[];
  rent?: MovieWatchProviders200ResultsZARentItem[];
  buy?: MovieWatchProviders200ResultsZABuyItem[];
};
