/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsLTBuyItem } from "./movieWatchProviders200ResultsLTBuyItem";
import type { MovieWatchProviders200ResultsLTFlatrateItem } from "./movieWatchProviders200ResultsLTFlatrateItem";
import type { MovieWatchProviders200ResultsLTRentItem } from "./movieWatchProviders200ResultsLTRentItem";

export type MovieWatchProviders200ResultsLT = {
  link?: string;
  rent?: MovieWatchProviders200ResultsLTRentItem[];
  buy?: MovieWatchProviders200ResultsLTBuyItem[];
  flatrate?: MovieWatchProviders200ResultsLTFlatrateItem[];
};
