/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsIDFlatrateItem } from "./movieWatchProviders200ResultsIDFlatrateItem";

export type MovieWatchProviders200ResultsID = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsIDFlatrateItem[];
};
