/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type MovieTranslations200TranslationsItemData = {
  homepage?: string;
  overview?: string;
  runtime?: number;
  tagline?: string;
  title?: string;
};
