/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsPHFlatrateItem } from "./movieWatchProviders200ResultsPHFlatrateItem";

export type MovieWatchProviders200ResultsPH = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsPHFlatrateItem[];
};
