/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsTHFlatrateItem } from "./movieWatchProviders200ResultsTHFlatrateItem";

export type MovieWatchProviders200ResultsTH = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsTHFlatrateItem[];
};
