/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsYEFlatrateItem } from "./movieWatchProviders200ResultsYEFlatrateItem";

export type MovieWatchProviders200ResultsYE = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsYEFlatrateItem[];
};
