/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsHKFlatrateItem } from "./movieWatchProviders200ResultsHKFlatrateItem";

export type MovieWatchProviders200ResultsHK = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsHKFlatrateItem[];
};
