/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MoviePopularList200ResultsItem } from "./moviePopularList200ResultsItem";

export type MoviePopularList200 = {
  page?: number;
  results?: MoviePopularList200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
