/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsUSBuyItem } from "./movieWatchProviders200ResultsUSBuyItem";
import type { MovieWatchProviders200ResultsUSFlatrateItem } from "./movieWatchProviders200ResultsUSFlatrateItem";
import type { MovieWatchProviders200ResultsUSRentItem } from "./movieWatchProviders200ResultsUSRentItem";

export type MovieWatchProviders200ResultsUS = {
  link?: string;
  rent?: MovieWatchProviders200ResultsUSRentItem[];
  flatrate?: MovieWatchProviders200ResultsUSFlatrateItem[];
  buy?: MovieWatchProviders200ResultsUSBuyItem[];
};
