/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieChanges200ChangesItemItemsItemValuePoster } from "./movieChanges200ChangesItemItemsItemValuePoster";

export type MovieChanges200ChangesItemItemsItemValue = {
  poster?: MovieChanges200ChangesItemItemsItemValuePoster;
};
