/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsRSBuyItem } from "./movieWatchProviders200ResultsRSBuyItem";
import type { MovieWatchProviders200ResultsRSFlatrateItem } from "./movieWatchProviders200ResultsRSFlatrateItem";

export type MovieWatchProviders200ResultsRS = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsRSFlatrateItem[];
  buy?: MovieWatchProviders200ResultsRSBuyItem[];
};
