/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieReleaseDates200ResultsItem } from "./movieReleaseDates200ResultsItem";

export type MovieReleaseDates200 = {
  id?: number;
  results?: MovieReleaseDates200ResultsItem[];
};
