/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsFJBuyItem } from "./movieWatchProviders200ResultsFJBuyItem";

export type MovieWatchProviders200ResultsFJ = {
  link?: string;
  buy?: MovieWatchProviders200ResultsFJBuyItem[];
};
