/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type MovieWatchProviders200ResultsBABuyItem = {
  logo_path?: string;
  provider_id?: number;
  provider_name?: string;
  display_priority?: number;
};
