/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsPEBuyItem } from "./movieWatchProviders200ResultsPEBuyItem";
import type { MovieWatchProviders200ResultsPEFlatrateItem } from "./movieWatchProviders200ResultsPEFlatrateItem";
import type { MovieWatchProviders200ResultsPERentItem } from "./movieWatchProviders200ResultsPERentItem";

export type MovieWatchProviders200ResultsPE = {
  link?: string;
  rent?: MovieWatchProviders200ResultsPERentItem[];
  buy?: MovieWatchProviders200ResultsPEBuyItem[];
  flatrate?: MovieWatchProviders200ResultsPEFlatrateItem[];
};
