/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsMZBuyItem } from "./movieWatchProviders200ResultsMZBuyItem";
import type { MovieWatchProviders200ResultsMZRentItem } from "./movieWatchProviders200ResultsMZRentItem";

export type MovieWatchProviders200ResultsMZ = {
  link?: string;
  rent?: MovieWatchProviders200ResultsMZRentItem[];
  buy?: MovieWatchProviders200ResultsMZBuyItem[];
};
