/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsIQFlatrateItem } from "./movieWatchProviders200ResultsIQFlatrateItem";

export type MovieWatchProviders200ResultsIQ = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsIQFlatrateItem[];
};
