/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieReviews200ResultsItem } from "./movieReviews200ResultsItem";

export type MovieReviews200 = {
  id?: number;
  page?: number;
  results?: MovieReviews200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
