/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsOMBuyItem } from "./movieWatchProviders200ResultsOMBuyItem";
import type { MovieWatchProviders200ResultsOMFlatrateItem } from "./movieWatchProviders200ResultsOMFlatrateItem";
import type { MovieWatchProviders200ResultsOMRentItem } from "./movieWatchProviders200ResultsOMRentItem";

export type MovieWatchProviders200ResultsOM = {
  link?: string;
  buy?: MovieWatchProviders200ResultsOMBuyItem[];
  rent?: MovieWatchProviders200ResultsOMRentItem[];
  flatrate?: MovieWatchProviders200ResultsOMFlatrateItem[];
};
