/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieAccountStates200Rated } from "./movieAccountStates200Rated";

export type MovieAccountStates200 = {
  id?: number;
  favorite?: boolean;
  rated?: MovieAccountStates200Rated;
  watchlist?: boolean;
};
