/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsSIBuyItem } from "./movieWatchProviders200ResultsSIBuyItem";
import type { MovieWatchProviders200ResultsSIFlatrateItem } from "./movieWatchProviders200ResultsSIFlatrateItem";

export type MovieWatchProviders200ResultsSI = {
  link?: string;
  buy?: MovieWatchProviders200ResultsSIBuyItem[];
  flatrate?: MovieWatchProviders200ResultsSIFlatrateItem[];
};
