/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieKeywords200KeywordsItem } from "./movieKeywords200KeywordsItem";

export type MovieKeywords200 = {
  id?: number;
  keywords?: MovieKeywords200KeywordsItem[];
};
