/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieChanges200ChangesItemItemsItem } from "./movieChanges200ChangesItemItemsItem";

export type MovieChanges200ChangesItem = {
  key?: string;
  items?: MovieChanges200ChangesItemItemsItem[];
};
