/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsGTFlatrateItem } from "./movieWatchProviders200ResultsGTFlatrateItem";

export type MovieWatchProviders200ResultsGT = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsGTFlatrateItem[];
};
