/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsESAdsItem } from "./movieWatchProviders200ResultsESAdsItem";
import type { MovieWatchProviders200ResultsESBuyItem } from "./movieWatchProviders200ResultsESBuyItem";
import type { MovieWatchProviders200ResultsESFlatrateItem } from "./movieWatchProviders200ResultsESFlatrateItem";
import type { MovieWatchProviders200ResultsESRentItem } from "./movieWatchProviders200ResultsESRentItem";

export type MovieWatchProviders200ResultsES = {
  link?: string;
  rent?: MovieWatchProviders200ResultsESRentItem[];
  ads?: MovieWatchProviders200ResultsESAdsItem[];
  flatrate?: MovieWatchProviders200ResultsESFlatrateItem[];
  buy?: MovieWatchProviders200ResultsESBuyItem[];
};
