/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsPKFlatrateItem } from "./movieWatchProviders200ResultsPKFlatrateItem";

export type MovieWatchProviders200ResultsPK = {
  link?: string;
  flatrate?: MovieWatchProviders200ResultsPKFlatrateItem[];
};
