/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { MovieWatchProviders200ResultsMUBuyItem } from "./movieWatchProviders200ResultsMUBuyItem";
import type { MovieWatchProviders200ResultsMURentItem } from "./movieWatchProviders200ResultsMURentItem";

export type MovieWatchProviders200ResultsMU = {
  link?: string;
  buy?: MovieWatchProviders200ResultsMUBuyItem[];
  rent?: MovieWatchProviders200ResultsMURentItem[];
};
