/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type PersonImages200ProfilesItem = {
  aspect_ratio?: number;
  height?: number;
  iso_639_1?: unknown;
  file_path?: string;
  vote_average?: number;
  vote_count?: number;
  width?: number;
};
