/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { PersonChanges200ChangesItemItemsItem } from "./personChanges200ChangesItemItemsItem";

export type PersonChanges200ChangesItem = {
  key?: string;
  items?: PersonChanges200ChangesItemItemsItem[];
};
