/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { PersonImages200ProfilesItem } from "./personImages200ProfilesItem";

export type PersonImages200 = {
  id?: number;
  profiles?: PersonImages200ProfilesItem[];
};
