/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { PersonChanges200ChangesItem } from "./personChanges200ChangesItem";

export type PersonChanges200 = {
  changes?: PersonChanges200ChangesItem[];
};
