/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { PersonTaggedImages200ResultsItem } from "./personTaggedImages200ResultsItem";

export type PersonTaggedImages200 = {
  id?: number;
  page?: number;
  results?: PersonTaggedImages200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
