/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { SearchCollection200ResultsItem } from "./searchCollection200ResultsItem";

export type SearchCollection200 = {
  page?: number;
  results?: SearchCollection200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
