/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { SearchTv200ResultsItem } from "./searchTv200ResultsItem";

export type SearchTv200 = {
  page?: number;
  results?: SearchTv200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
