/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TrendingMovies200ResultsItem } from "./trendingMovies200ResultsItem";

export type TrendingMovies200 = {
  page?: number;
  results?: TrendingMovies200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
