/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TrendingTv200ResultsItem } from "./trendingTv200ResultsItem";

export type TrendingTv200 = {
  page?: number;
  results?: TrendingTv200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
