/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TrendingPeopleParams = {
  /**
   * `ISO-639-1`-`ISO-3166-1` code
   */
  language?: string;
};
