/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TrendingPeople200ResultsItem } from "./trendingPeople200ResultsItem";

export type TrendingPeople200 = {
  page?: number;
  results?: TrendingPeople200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
