/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvEpisodeChangesById200ChangesItemItemsItem } from "./tvEpisodeChangesById200ChangesItemItemsItem";

export type TvEpisodeChangesById200ChangesItem = {
  key?: string;
  items?: TvEpisodeChangesById200ChangesItemItemsItem[];
};
