/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvEpisodeImages200StillsItem } from "./tvEpisodeImages200StillsItem";

export type TvEpisodeImages200 = {
  id?: number;
  stills?: TvEpisodeImages200StillsItem[];
};
