/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvEpisodeTranslations200TranslationsItem } from "./tvEpisodeTranslations200TranslationsItem";

export type TvEpisodeTranslations200 = {
  id?: number;
  translations?: TvEpisodeTranslations200TranslationsItem[];
};
