/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvEpisodeChangesById200ChangesItem } from "./tvEpisodeChangesById200ChangesItem";

export type TvEpisodeChangesById200 = {
  changes?: TvEpisodeChangesById200ChangesItem[];
};
