/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvEpisodeChangesById200ChangesItemItemsItem = {
  id?: string;
  action?: string;
  time?: string;
  value?: string;
};
