/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvEpisodeAccountStatesParams = {
  session_id?: string;
  guest_session_id?: string;
};
