/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvEpisodeGroupDetails200GroupsItemEpisodesItem } from "./tvEpisodeGroupDetails200GroupsItemEpisodesItem";

export type TvEpisodeGroupDetails200GroupsItem = {
  id?: string;
  name?: string;
  order?: number;
  episodes?: TvEpisodeGroupDetails200GroupsItemEpisodesItem[];
  locked?: boolean;
};
