/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvEpisodeVideos200ResultsItem } from "./tvEpisodeVideos200ResultsItem";

export type TvEpisodeVideos200 = {
  id?: number;
  results?: TvEpisodeVideos200ResultsItem[];
};
