/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsSIFlatrateItem } from "./tvSeriesWatchProviders200ResultsSIFlatrateItem";

export type TvSeriesWatchProviders200ResultsSI = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsSIFlatrateItem[];
};
