/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsNLBuyItem } from "./tvSeriesWatchProviders200ResultsNLBuyItem";
import type { TvSeriesWatchProviders200ResultsNLFlatrateItem } from "./tvSeriesWatchProviders200ResultsNLFlatrateItem";

export type TvSeriesWatchProviders200ResultsNL = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsNLFlatrateItem[];
  buy?: TvSeriesWatchProviders200ResultsNLBuyItem[];
};
