/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsBBFlatrateItem } from "./tvSeasonWatchProviders200ResultsBBFlatrateItem";

export type TvSeasonWatchProviders200ResultsBB = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsBBFlatrateItem[];
};
