/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsDEBuyItem } from "./tvSeasonWatchProviders200ResultsDEBuyItem";
import type { TvSeasonWatchProviders200ResultsDEFlatrateItem } from "./tvSeasonWatchProviders200ResultsDEFlatrateItem";

export type TvSeasonWatchProviders200ResultsDE = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsDEFlatrateItem[];
  buy?: TvSeasonWatchProviders200ResultsDEBuyItem[];
};
