/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsMYFlatrateItem } from "./tvSeriesWatchProviders200ResultsMYFlatrateItem";

export type TvSeriesWatchProviders200ResultsMY = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsMYFlatrateItem[];
};
