/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsTRFlatrateItem } from "./tvSeriesWatchProviders200ResultsTRFlatrateItem";

export type TvSeriesWatchProviders200ResultsTR = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsTRFlatrateItem[];
};
