/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesOnTheAirList200ResultsItem } from "./tvSeriesOnTheAirList200ResultsItem";

export type TvSeriesOnTheAirList200 = {
  page?: number;
  results?: TvSeriesOnTheAirList200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
