/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsNOBuyItem } from "./tvSeriesWatchProviders200ResultsNOBuyItem";
import type { TvSeriesWatchProviders200ResultsNOFlatrateItem } from "./tvSeriesWatchProviders200ResultsNOFlatrateItem";

export type TvSeriesWatchProviders200ResultsNO = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsNOFlatrateItem[];
  buy?: TvSeriesWatchProviders200ResultsNOBuyItem[];
};
