/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsNIFlatrateItem } from "./tvSeasonWatchProviders200ResultsNIFlatrateItem";

export type TvSeasonWatchProviders200ResultsNI = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsNIFlatrateItem[];
};
