/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsIEBuyItem } from "./tvSeasonWatchProviders200ResultsIEBuyItem";
import type { TvSeasonWatchProviders200ResultsIEFlatrateItem } from "./tvSeasonWatchProviders200ResultsIEFlatrateItem";

export type TvSeasonWatchProviders200ResultsIE = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsIEFlatrateItem[];
  buy?: TvSeasonWatchProviders200ResultsIEBuyItem[];
};
