/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsKEFlatrateItem } from "./tvSeasonWatchProviders200ResultsKEFlatrateItem";

export type TvSeasonWatchProviders200ResultsKE = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsKEFlatrateItem[];
};
