/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsOMFlatrateItem } from "./tvSeasonWatchProviders200ResultsOMFlatrateItem";

export type TvSeasonWatchProviders200ResultsOM = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsOMFlatrateItem[];
};
