/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsPTFlatrateItem } from "./tvSeriesWatchProviders200ResultsPTFlatrateItem";

export type TvSeriesWatchProviders200ResultsPT = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsPTFlatrateItem[];
};
