/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsUYFlatrateItem } from "./tvSeasonWatchProviders200ResultsUYFlatrateItem";

export type TvSeasonWatchProviders200ResultsUY = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsUYFlatrateItem[];
};
