/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsBGFlatrateItem } from "./tvSeasonWatchProviders200ResultsBGFlatrateItem";

export type TvSeasonWatchProviders200ResultsBG = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsBGFlatrateItem[];
};
