/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsBOFlatrateItem } from "./tvSeasonWatchProviders200ResultsBOFlatrateItem";

export type TvSeasonWatchProviders200ResultsBO = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsBOFlatrateItem[];
};
