/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsAUBuyItem } from "./tvSeriesWatchProviders200ResultsAUBuyItem";
import type { TvSeriesWatchProviders200ResultsAUFlatrateItem } from "./tvSeriesWatchProviders200ResultsAUFlatrateItem";

export type TvSeriesWatchProviders200ResultsAU = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsAUFlatrateItem[];
  buy?: TvSeriesWatchProviders200ResultsAUBuyItem[];
};
