/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsFRBuyItem } from "./tvSeriesWatchProviders200ResultsFRBuyItem";
import type { TvSeriesWatchProviders200ResultsFRFlatrateItem } from "./tvSeriesWatchProviders200ResultsFRFlatrateItem";

export type TvSeriesWatchProviders200ResultsFR = {
  link?: string;
  buy?: TvSeriesWatchProviders200ResultsFRBuyItem[];
  flatrate?: TvSeriesWatchProviders200ResultsFRFlatrateItem[];
};
