/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsUSBuyItem } from "./tvSeasonWatchProviders200ResultsUSBuyItem";
import type { TvSeasonWatchProviders200ResultsUSFlatrateItem } from "./tvSeasonWatchProviders200ResultsUSFlatrateItem";

export type TvSeasonWatchProviders200ResultsUS = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsUSFlatrateItem[];
  buy?: TvSeasonWatchProviders200ResultsUSBuyItem[];
};
