/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeriesAlternativeTitles200ResultsItem = {
  iso_3166_1?: string;
  title?: string;
  type?: string;
};
