/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsECFlatrateItem } from "./tvSeasonWatchProviders200ResultsECFlatrateItem";

export type TvSeasonWatchProviders200ResultsEC = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsECFlatrateItem[];
};
