/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesRecommendations200ResultsItem } from "./tvSeriesRecommendations200ResultsItem";

export type TvSeriesRecommendations200 = {
  page?: number;
  results?: TvSeriesRecommendations200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
