/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsGQFlatrateItem } from "./tvSeasonWatchProviders200ResultsGQFlatrateItem";

export type TvSeasonWatchProviders200ResultsGQ = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsGQFlatrateItem[];
};
