/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsLCFlatrateItem } from "./tvSeasonWatchProviders200ResultsLCFlatrateItem";

export type TvSeasonWatchProviders200ResultsLC = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsLCFlatrateItem[];
};
