/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesVideos200ResultsItem } from "./tvSeriesVideos200ResultsItem";

export type TvSeriesVideos200 = {
  id?: number;
  results?: TvSeriesVideos200ResultsItem[];
};
