/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonAccountStates200ResultsItem } from "./tvSeasonAccountStates200ResultsItem";

export type TvSeasonAccountStates200 = {
  id?: number;
  results?: TvSeasonAccountStates200ResultsItem[];
};
