/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsSEBuyItem } from "./tvSeriesWatchProviders200ResultsSEBuyItem";
import type { TvSeriesWatchProviders200ResultsSEFlatrateItem } from "./tvSeriesWatchProviders200ResultsSEFlatrateItem";

export type TvSeriesWatchProviders200ResultsSE = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsSEFlatrateItem[];
  buy?: TvSeriesWatchProviders200ResultsSEBuyItem[];
};
