/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsIEBuyItem } from "./tvSeriesWatchProviders200ResultsIEBuyItem";
import type { TvSeriesWatchProviders200ResultsIEFlatrateItem } from "./tvSeriesWatchProviders200ResultsIEFlatrateItem";

export type TvSeriesWatchProviders200ResultsIE = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsIEFlatrateItem[];
  buy?: TvSeriesWatchProviders200ResultsIEBuyItem[];
};
