/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsMZFlatrateItem } from "./tvSeasonWatchProviders200ResultsMZFlatrateItem";

export type TvSeasonWatchProviders200ResultsMZ = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsMZFlatrateItem[];
};
