/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsGHFlatrateItem } from "./tvSeriesWatchProviders200ResultsGHFlatrateItem";

export type TvSeriesWatchProviders200ResultsGH = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsGHFlatrateItem[];
};
