/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsSNFlatrateItem } from "./tvSeasonWatchProviders200ResultsSNFlatrateItem";

export type TvSeasonWatchProviders200ResultsSN = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsSNFlatrateItem[];
};
