/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsCRFlatrateItem } from "./tvSeasonWatchProviders200ResultsCRFlatrateItem";

export type TvSeasonWatchProviders200ResultsCR = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsCRFlatrateItem[];
};
