/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsBEBuyItem } from "./tvSeasonWatchProviders200ResultsBEBuyItem";
import type { TvSeasonWatchProviders200ResultsBEFlatrateItem } from "./tvSeasonWatchProviders200ResultsBEFlatrateItem";

export type TvSeasonWatchProviders200ResultsBE = {
  link?: string;
  buy?: TvSeasonWatchProviders200ResultsBEBuyItem[];
  flatrate?: TvSeasonWatchProviders200ResultsBEFlatrateItem[];
};
