/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesKeywords200ResultsItem } from "./tvSeriesKeywords200ResultsItem";

export type TvSeriesKeywords200 = {
  id?: number;
  results?: TvSeriesKeywords200ResultsItem[];
};
