/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsSGFlatrateItem } from "./tvSeriesWatchProviders200ResultsSGFlatrateItem";

export type TvSeriesWatchProviders200ResultsSG = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsSGFlatrateItem[];
};
