/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsCOFlatrateItem } from "./tvSeriesWatchProviders200ResultsCOFlatrateItem";

export type TvSeriesWatchProviders200ResultsCO = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsCOFlatrateItem[];
};
