/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsGBBuyItem } from "./tvSeriesWatchProviders200ResultsGBBuyItem";
import type { TvSeriesWatchProviders200ResultsGBFlatrateItem } from "./tvSeriesWatchProviders200ResultsGBFlatrateItem";

export type TvSeriesWatchProviders200ResultsGB = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsGBFlatrateItem[];
  buy?: TvSeriesWatchProviders200ResultsGBBuyItem[];
};
