/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsPAFlatrateItem } from "./tvSeriesWatchProviders200ResultsPAFlatrateItem";

export type TvSeriesWatchProviders200ResultsPA = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsPAFlatrateItem[];
};
