/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsCABuyItem } from "./tvSeriesWatchProviders200ResultsCABuyItem";
import type { TvSeriesWatchProviders200ResultsCAFlatrateItem } from "./tvSeriesWatchProviders200ResultsCAFlatrateItem";

export type TvSeriesWatchProviders200ResultsCA = {
  link?: string;
  buy?: TvSeriesWatchProviders200ResultsCABuyItem[];
  flatrate?: TvSeriesWatchProviders200ResultsCAFlatrateItem[];
};
