/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsCIFlatrateItem } from "./tvSeasonWatchProviders200ResultsCIFlatrateItem";

export type TvSeasonWatchProviders200ResultsCI = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsCIFlatrateItem[];
};
