/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesChanges200ChangesItemItemsItemOriginalValuePoster } from "./tvSeriesChanges200ChangesItemItemsItemOriginalValuePoster";

export type TvSeriesChanges200ChangesItemItemsItemOriginalValue = {
  poster?: TvSeriesChanges200ChangesItemItemsItemOriginalValuePoster;
};
