/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsVEFlatrateItem } from "./tvSeriesWatchProviders200ResultsVEFlatrateItem";

export type TvSeriesWatchProviders200ResultsVE = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsVEFlatrateItem[];
};
