/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsZMFlatrateItem } from "./tvSeasonWatchProviders200ResultsZMFlatrateItem";

export type TvSeasonWatchProviders200ResultsZM = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsZMFlatrateItem[];
};
