/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonAccountStates200ResultsItemRated } from "./tvSeasonAccountStates200ResultsItemRated";

export type TvSeasonAccountStates200ResultsItem = {
  id?: number;
  episode_number?: number;
  rated?: TvSeasonAccountStates200ResultsItemRated;
};
