/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsFIBuyItem } from "./tvSeasonWatchProviders200ResultsFIBuyItem";
import type { TvSeasonWatchProviders200ResultsFIFlatrateItem } from "./tvSeasonWatchProviders200ResultsFIFlatrateItem";

export type TvSeasonWatchProviders200ResultsFI = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsFIFlatrateItem[];
  buy?: TvSeasonWatchProviders200ResultsFIBuyItem[];
};
