/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsQAFlatrateItem } from "./tvSeasonWatchProviders200ResultsQAFlatrateItem";

export type TvSeasonWatchProviders200ResultsQA = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsQAFlatrateItem[];
};
