/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsNGFlatrateItem } from "./tvSeriesWatchProviders200ResultsNGFlatrateItem";

export type TvSeriesWatchProviders200ResultsNG = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsNGFlatrateItem[];
};
