/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesAiringTodayList200ResultsItem } from "./tvSeriesAiringTodayList200ResultsItem";

export type TvSeriesAiringTodayList200 = {
  page?: number;
  results?: TvSeriesAiringTodayList200ResultsItem[];
  total_pages?: number;
  total_results?: number;
};
