/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsNGFlatrateItem } from "./tvSeasonWatchProviders200ResultsNGFlatrateItem";

export type TvSeasonWatchProviders200ResultsNG = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsNGFlatrateItem[];
};
