/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsLBFlatrateItem } from "./tvSeriesWatchProviders200ResultsLBFlatrateItem";

export type TvSeriesWatchProviders200ResultsLB = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsLBFlatrateItem[];
};
