/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsMEFlatrateItem } from "./tvSeasonWatchProviders200ResultsMEFlatrateItem";

export type TvSeasonWatchProviders200ResultsME = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsMEFlatrateItem[];
};
