/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsMDFlatrateItem } from "./tvSeasonWatchProviders200ResultsMDFlatrateItem";

export type TvSeasonWatchProviders200ResultsMD = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsMDFlatrateItem[];
};
