/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesAlternativeTitles200ResultsItem } from "./tvSeriesAlternativeTitles200ResultsItem";

export type TvSeriesAlternativeTitles200 = {
  id?: number;
  results?: TvSeriesAlternativeTitles200ResultsItem[];
};
