/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesCredits200CastItem } from "./tvSeriesCredits200CastItem";
import type { TvSeriesCredits200CrewItem } from "./tvSeriesCredits200CrewItem";

export type TvSeriesCredits200 = {
  cast?: TvSeriesCredits200CastItem[];
  crew?: TvSeriesCredits200CrewItem[];
  id?: number;
};
