/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesChanges200ChangesItemItemsItemValuePoster } from "./tvSeriesChanges200ChangesItemItemsItemValuePoster";

export type TvSeriesChanges200ChangesItemItemsItemValue = {
  poster?: TvSeriesChanges200ChangesItemItemsItemValuePoster;
};
