/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsMXFlatrateItem } from "./tvSeasonWatchProviders200ResultsMXFlatrateItem";

export type TvSeasonWatchProviders200ResultsMX = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsMXFlatrateItem[];
};
