/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsGFFlatrateItem } from "./tvSeriesWatchProviders200ResultsGFFlatrateItem";

export type TvSeriesWatchProviders200ResultsGF = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsGFFlatrateItem[];
};
