/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsLBFlatrateItem } from "./tvSeasonWatchProviders200ResultsLBFlatrateItem";

export type TvSeasonWatchProviders200ResultsLB = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsLBFlatrateItem[];
};
