/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsJMFlatrateItem } from "./tvSeasonWatchProviders200ResultsJMFlatrateItem";

export type TvSeasonWatchProviders200ResultsJM = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsJMFlatrateItem[];
};
