/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsCZFlatrateItem } from "./tvSeasonWatchProviders200ResultsCZFlatrateItem";

export type TvSeasonWatchProviders200ResultsCZ = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsCZFlatrateItem[];
};
