/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonVideos200ResultsItem } from "./tvSeasonVideos200ResultsItem";

export type TvSeasonVideos200 = {
  id?: number;
  results?: TvSeasonVideos200ResultsItem[];
};
