/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesAccountStates200Rated } from "./tvSeriesAccountStates200Rated";

export type TvSeriesAccountStates200 = {
  id?: number;
  favorite?: boolean;
  rated?: TvSeriesAccountStates200Rated;
  watchlist?: boolean;
};
