/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsECFlatrateItem } from "./tvSeriesWatchProviders200ResultsECFlatrateItem";

export type TvSeriesWatchProviders200ResultsEC = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsECFlatrateItem[];
};
