/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeriesContentRatings200ResultsItem = {
  descriptors?: unknown[];
  iso_3166_1?: string;
  rating?: string;
};
