/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsSVFlatrateItem } from "./tvSeasonWatchProviders200ResultsSVFlatrateItem";

export type TvSeasonWatchProviders200ResultsSV = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsSVFlatrateItem[];
};
