/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsKRFlatrateItem } from "./tvSeriesWatchProviders200ResultsKRFlatrateItem";

export type TvSeriesWatchProviders200ResultsKR = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsKRFlatrateItem[];
};
