/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsCZFlatrateItem } from "./tvSeriesWatchProviders200ResultsCZFlatrateItem";

export type TvSeriesWatchProviders200ResultsCZ = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsCZFlatrateItem[];
};
