/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsARFlatrateItem } from "./tvSeasonWatchProviders200ResultsARFlatrateItem";

export type TvSeasonWatchProviders200ResultsAR = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsARFlatrateItem[];
};
