/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsDOFlatrateItem } from "./tvSeriesWatchProviders200ResultsDOFlatrateItem";

export type TvSeriesWatchProviders200ResultsDO = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsDOFlatrateItem[];
};
