/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsSAFlatrateItem } from "./tvSeriesWatchProviders200ResultsSAFlatrateItem";

export type TvSeriesWatchProviders200ResultsSA = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsSAFlatrateItem[];
};
