/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsMUFlatrateItem } from "./tvSeriesWatchProviders200ResultsMUFlatrateItem";

export type TvSeriesWatchProviders200ResultsMU = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsMUFlatrateItem[];
};
