/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsVEFlatrateItem } from "./tvSeasonWatchProviders200ResultsVEFlatrateItem";

export type TvSeasonWatchProviders200ResultsVE = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsVEFlatrateItem[];
};
