/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsCLFlatrateItem } from "./tvSeriesWatchProviders200ResultsCLFlatrateItem";

export type TvSeriesWatchProviders200ResultsCL = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsCLFlatrateItem[];
};
