/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsNOFlatrateItem } from "./tvSeasonWatchProviders200ResultsNOFlatrateItem";

export type TvSeasonWatchProviders200ResultsNO = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsNOFlatrateItem[];
};
