/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsPEFlatrateItem } from "./tvSeriesWatchProviders200ResultsPEFlatrateItem";

export type TvSeriesWatchProviders200ResultsPE = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsPEFlatrateItem[];
};
