/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsMKFlatrateItem } from "./tvSeriesWatchProviders200ResultsMKFlatrateItem";

export type TvSeriesWatchProviders200ResultsMK = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsMKFlatrateItem[];
};
