/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeasonDetails200NetworksItem = {
  id?: number;
  logo_path?: string;
  name?: string;
  origin_country?: string;
};
