/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsHKFlatrateItem } from "./tvSeasonWatchProviders200ResultsHKFlatrateItem";

export type TvSeasonWatchProviders200ResultsHK = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsHKFlatrateItem[];
};
