/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsHUFlatrateItem } from "./tvSeriesWatchProviders200ResultsHUFlatrateItem";

export type TvSeriesWatchProviders200ResultsHU = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsHUFlatrateItem[];
};
