/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsUGFlatrateItem } from "./tvSeriesWatchProviders200ResultsUGFlatrateItem";

export type TvSeriesWatchProviders200ResultsUG = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsUGFlatrateItem[];
};
