/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsAUBuyItem } from "./tvSeasonWatchProviders200ResultsAUBuyItem";
import type { TvSeasonWatchProviders200ResultsAUFlatrateItem } from "./tvSeasonWatchProviders200ResultsAUFlatrateItem";

export type TvSeasonWatchProviders200ResultsAU = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsAUFlatrateItem[];
  buy?: TvSeasonWatchProviders200ResultsAUBuyItem[];
};
