/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonChangesById200ChangesItemItemsItemValue } from "./tvSeasonChangesById200ChangesItemItemsItemValue";

export type TvSeasonChangesById200ChangesItemItemsItem = {
  id?: string;
  action?: string;
  time?: string;
  value?: TvSeasonChangesById200ChangesItemItemsItemValue;
};
