/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsRUFlatrateItem } from "./tvSeasonWatchProviders200ResultsRUFlatrateItem";

export type TvSeasonWatchProviders200ResultsRU = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsRUFlatrateItem[];
};
