/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsSVFlatrateItem } from "./tvSeriesWatchProviders200ResultsSVFlatrateItem";

export type TvSeriesWatchProviders200ResultsSV = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsSVFlatrateItem[];
};
