/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsSKFlatrateItem } from "./tvSeriesWatchProviders200ResultsSKFlatrateItem";

export type TvSeriesWatchProviders200ResultsSK = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsSKFlatrateItem[];
};
