/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsHUFlatrateItem } from "./tvSeasonWatchProviders200ResultsHUFlatrateItem";

export type TvSeasonWatchProviders200ResultsHU = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsHUFlatrateItem[];
};
