/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsKEFlatrateItem } from "./tvSeriesWatchProviders200ResultsKEFlatrateItem";

export type TvSeriesWatchProviders200ResultsKE = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsKEFlatrateItem[];
};
