/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsHNFlatrateItem } from "./tvSeriesWatchProviders200ResultsHNFlatrateItem";

export type TvSeriesWatchProviders200ResultsHN = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsHNFlatrateItem[];
};
