/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsPLBuyItem } from "./tvSeasonWatchProviders200ResultsPLBuyItem";
import type { TvSeasonWatchProviders200ResultsPLFlatrateItem } from "./tvSeasonWatchProviders200ResultsPLFlatrateItem";

export type TvSeasonWatchProviders200ResultsPL = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsPLFlatrateItem[];
  buy?: TvSeasonWatchProviders200ResultsPLBuyItem[];
};
