/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeriesDetails200CreatedByItem = {
  id?: number;
  credit_id?: string;
  name?: string;
  gender?: number;
  profile_path?: string;
};
