/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsBRFlatrateItem } from "./tvSeasonWatchProviders200ResultsBRFlatrateItem";

export type TvSeasonWatchProviders200ResultsBR = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsBRFlatrateItem[];
};
