/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsMZFlatrateItem } from "./tvSeriesWatchProviders200ResultsMZFlatrateItem";

export type TvSeriesWatchProviders200ResultsMZ = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsMZFlatrateItem[];
};
