/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonChangesById200ChangesItem } from "./tvSeasonChangesById200ChangesItem";

export type TvSeasonChangesById200 = {
  changes?: TvSeasonChangesById200ChangesItem[];
};
