/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsRSFlatrateItem } from "./tvSeasonWatchProviders200ResultsRSFlatrateItem";

export type TvSeasonWatchProviders200ResultsRS = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsRSFlatrateItem[];
};
