/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsCMFlatrateItem } from "./tvSeasonWatchProviders200ResultsCMFlatrateItem";

export type TvSeasonWatchProviders200ResultsCM = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsCMFlatrateItem[];
};
