/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsMYFlatrateItem } from "./tvSeasonWatchProviders200ResultsMYFlatrateItem";

export type TvSeasonWatchProviders200ResultsMY = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsMYFlatrateItem[];
};
