/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsATBuyItem } from "./tvSeriesWatchProviders200ResultsATBuyItem";
import type { TvSeriesWatchProviders200ResultsATFlatrateItem } from "./tvSeriesWatchProviders200ResultsATFlatrateItem";

export type TvSeriesWatchProviders200ResultsAT = {
  link?: string;
  buy?: TvSeriesWatchProviders200ResultsATBuyItem[];
  flatrate?: TvSeriesWatchProviders200ResultsATFlatrateItem[];
};
