/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsRSFlatrateItem } from "./tvSeriesWatchProviders200ResultsRSFlatrateItem";

export type TvSeriesWatchProviders200ResultsRS = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsRSFlatrateItem[];
};
