/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsCHBuyItem } from "./tvSeriesWatchProviders200ResultsCHBuyItem";
import type { TvSeriesWatchProviders200ResultsCHFlatrateItem } from "./tvSeriesWatchProviders200ResultsCHFlatrateItem";

export type TvSeriesWatchProviders200ResultsCH = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsCHFlatrateItem[];
  buy?: TvSeriesWatchProviders200ResultsCHBuyItem[];
};
