/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsBGFlatrateItem } from "./tvSeriesWatchProviders200ResultsBGFlatrateItem";

export type TvSeriesWatchProviders200ResultsBG = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsBGFlatrateItem[];
};
