/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsILFlatrateItem } from "./tvSeriesWatchProviders200ResultsILFlatrateItem";

export type TvSeriesWatchProviders200ResultsIL = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsILFlatrateItem[];
};
