/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsROFlatrateItem } from "./tvSeasonWatchProviders200ResultsROFlatrateItem";

export type TvSeasonWatchProviders200ResultsRO = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsROFlatrateItem[];
};
