/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsIDFlatrateItem } from "./tvSeasonWatchProviders200ResultsIDFlatrateItem";

export type TvSeasonWatchProviders200ResultsID = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsIDFlatrateItem[];
};
