/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsJOFlatrateItem } from "./tvSeasonWatchProviders200ResultsJOFlatrateItem";

export type TvSeasonWatchProviders200ResultsJO = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsJOFlatrateItem[];
};
