/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsMKFlatrateItem } from "./tvSeasonWatchProviders200ResultsMKFlatrateItem";

export type TvSeasonWatchProviders200ResultsMK = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsMKFlatrateItem[];
};
