/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsBHFlatrateItem } from "./tvSeasonWatchProviders200ResultsBHFlatrateItem";

export type TvSeasonWatchProviders200ResultsBH = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsBHFlatrateItem[];
};
