/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsCRFlatrateItem } from "./tvSeriesWatchProviders200ResultsCRFlatrateItem";

export type TvSeriesWatchProviders200ResultsCR = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsCRFlatrateItem[];
};
