/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsADFlatrateItem } from "./tvSeasonWatchProviders200ResultsADFlatrateItem";

export type TvSeasonWatchProviders200ResultsAD = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsADFlatrateItem[];
};
