/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsEGFlatrateItem } from "./tvSeriesWatchProviders200ResultsEGFlatrateItem";

export type TvSeriesWatchProviders200ResultsEG = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsEGFlatrateItem[];
};
