/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200Results } from "./tvSeasonWatchProviders200Results";

export type TvSeasonWatchProviders200 = {
  id?: number;
  results?: TvSeasonWatchProviders200Results;
};
