/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsCABuyItem } from "./tvSeasonWatchProviders200ResultsCABuyItem";
import type { TvSeasonWatchProviders200ResultsCAFlatrateItem } from "./tvSeasonWatchProviders200ResultsCAFlatrateItem";

export type TvSeasonWatchProviders200ResultsCA = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsCAFlatrateItem[];
  buy?: TvSeasonWatchProviders200ResultsCABuyItem[];
};
