/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonTranslations200TranslationsItemData } from "./tvSeasonTranslations200TranslationsItemData";

export type TvSeasonTranslations200TranslationsItem = {
  iso_3166_1?: string;
  iso_639_1?: string;
  name?: string;
  english_name?: string;
  data?: TvSeasonTranslations200TranslationsItemData;
};
