/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsTWFlatrateItem } from "./tvSeriesWatchProviders200ResultsTWFlatrateItem";

export type TvSeriesWatchProviders200ResultsTW = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsTWFlatrateItem[];
};
