/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsNZFlatrateItem } from "./tvSeriesWatchProviders200ResultsNZFlatrateItem";

export type TvSeriesWatchProviders200ResultsNZ = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsNZFlatrateItem[];
};
