/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsTTFlatrateItem } from "./tvSeasonWatchProviders200ResultsTTFlatrateItem";

export type TvSeasonWatchProviders200ResultsTT = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsTTFlatrateItem[];
};
