/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsTWFlatrateItem } from "./tvSeasonWatchProviders200ResultsTWFlatrateItem";

export type TvSeasonWatchProviders200ResultsTW = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsTWFlatrateItem[];
};
