/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesEpisodeGroups200ResultsItem } from "./tvSeriesEpisodeGroups200ResultsItem";

export type TvSeriesEpisodeGroups200 = {
  results?: TvSeriesEpisodeGroups200ResultsItem[];
  id?: number;
};
