/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsGTFlatrateItem } from "./tvSeasonWatchProviders200ResultsGTFlatrateItem";

export type TvSeasonWatchProviders200ResultsGT = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsGTFlatrateItem[];
};
