/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsSKFlatrateItem } from "./tvSeasonWatchProviders200ResultsSKFlatrateItem";

export type TvSeasonWatchProviders200ResultsSK = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsSKFlatrateItem[];
};
