/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsSCFlatrateItem } from "./tvSeasonWatchProviders200ResultsSCFlatrateItem";

export type TvSeasonWatchProviders200ResultsSC = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsSCFlatrateItem[];
};
