/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsESBuyItem } from "./tvSeasonWatchProviders200ResultsESBuyItem";
import type { TvSeasonWatchProviders200ResultsESFlatrateItem } from "./tvSeasonWatchProviders200ResultsESFlatrateItem";

export type TvSeasonWatchProviders200ResultsES = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsESFlatrateItem[];
  buy?: TvSeasonWatchProviders200ResultsESBuyItem[];
};
