/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsNEFlatrateItem } from "./tvSeriesWatchProviders200ResultsNEFlatrateItem";

export type TvSeriesWatchProviders200ResultsNE = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsNEFlatrateItem[];
};
