/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsAEFlatrateItem } from "./tvSeriesWatchProviders200ResultsAEFlatrateItem";

export type TvSeriesWatchProviders200ResultsAE = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsAEFlatrateItem[];
};
