/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsNZBuyItem } from "./tvSeasonWatchProviders200ResultsNZBuyItem";
import type { TvSeasonWatchProviders200ResultsNZFlatrateItem } from "./tvSeasonWatchProviders200ResultsNZFlatrateItem";

export type TvSeasonWatchProviders200ResultsNZ = {
  link?: string;
  buy?: TvSeasonWatchProviders200ResultsNZBuyItem[];
  flatrate?: TvSeasonWatchProviders200ResultsNZFlatrateItem[];
};
