/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsITBuyItem } from "./tvSeriesWatchProviders200ResultsITBuyItem";
import type { TvSeriesWatchProviders200ResultsITFlatrateItem } from "./tvSeriesWatchProviders200ResultsITFlatrateItem";

export type TvSeriesWatchProviders200ResultsIT = {
  link?: string;
  buy?: TvSeriesWatchProviders200ResultsITBuyItem[];
  flatrate?: TvSeriesWatchProviders200ResultsITFlatrateItem[];
};
