/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsITBuyItem } from "./tvSeasonWatchProviders200ResultsITBuyItem";
import type { TvSeasonWatchProviders200ResultsITFlatrateItem } from "./tvSeasonWatchProviders200ResultsITFlatrateItem";

export type TvSeasonWatchProviders200ResultsIT = {
  link?: string;
  buy?: TvSeasonWatchProviders200ResultsITBuyItem[];
  flatrate?: TvSeasonWatchProviders200ResultsITFlatrateItem[];
};
