/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsCOFlatrateItem } from "./tvSeasonWatchProviders200ResultsCOFlatrateItem";

export type TvSeasonWatchProviders200ResultsCO = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsCOFlatrateItem[];
};
