/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsDKFlatrateItem } from "./tvSeasonWatchProviders200ResultsDKFlatrateItem";

export type TvSeasonWatchProviders200ResultsDK = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsDKFlatrateItem[];
};
