/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsLTFlatrateItem } from "./tvSeriesWatchProviders200ResultsLTFlatrateItem";

export type TvSeriesWatchProviders200ResultsLT = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsLTFlatrateItem[];
};
