/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsTTFlatrateItem } from "./tvSeriesWatchProviders200ResultsTTFlatrateItem";

export type TvSeriesWatchProviders200ResultsTT = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsTTFlatrateItem[];
};
