/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsPAFlatrateItem } from "./tvSeasonWatchProviders200ResultsPAFlatrateItem";

export type TvSeasonWatchProviders200ResultsPA = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsPAFlatrateItem[];
};
