/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsDKFlatrateItem } from "./tvSeriesWatchProviders200ResultsDKFlatrateItem";

export type TvSeriesWatchProviders200ResultsDK = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsDKFlatrateItem[];
};
