/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsBSFlatrateItem } from "./tvSeasonWatchProviders200ResultsBSFlatrateItem";

export type TvSeasonWatchProviders200ResultsBS = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsBSFlatrateItem[];
};
