/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeriesVideosParams = {
  /**
   * filter the list results by language, supports more than one value by using a comma
   */
  include_video_language?: string;
  language?: string;
};
