/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsNEFlatrateItem } from "./tvSeasonWatchProviders200ResultsNEFlatrateItem";

export type TvSeasonWatchProviders200ResultsNE = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsNEFlatrateItem[];
};
