/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsBRFlatrateItem } from "./tvSeriesWatchProviders200ResultsBRFlatrateItem";

export type TvSeriesWatchProviders200ResultsBR = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsBRFlatrateItem[];
};
