/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsPYFlatrateItem } from "./tvSeasonWatchProviders200ResultsPYFlatrateItem";

export type TvSeasonWatchProviders200ResultsPY = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsPYFlatrateItem[];
};
