/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsZAFlatrateItem } from "./tvSeasonWatchProviders200ResultsZAFlatrateItem";

export type TvSeasonWatchProviders200ResultsZA = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsZAFlatrateItem[];
};
