/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsMGFlatrateItem } from "./tvSeasonWatchProviders200ResultsMGFlatrateItem";

export type TvSeasonWatchProviders200ResultsMG = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsMGFlatrateItem[];
};
