/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsNLBuyItem } from "./tvSeasonWatchProviders200ResultsNLBuyItem";
import type { TvSeasonWatchProviders200ResultsNLFlatrateItem } from "./tvSeasonWatchProviders200ResultsNLFlatrateItem";

export type TvSeasonWatchProviders200ResultsNL = {
  link?: string;
  buy?: TvSeasonWatchProviders200ResultsNLBuyItem[];
  flatrate?: TvSeasonWatchProviders200ResultsNLFlatrateItem[];
};
