/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonImages200PostersItem } from "./tvSeasonImages200PostersItem";

export type TvSeasonImages200 = {
  id?: number;
  posters?: TvSeasonImages200PostersItem[];
};
