/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsHRFlatrateItem } from "./tvSeasonWatchProviders200ResultsHRFlatrateItem";

export type TvSeasonWatchProviders200ResultsHR = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsHRFlatrateItem[];
};
