/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsARFlatrateItem } from "./tvSeriesWatchProviders200ResultsARFlatrateItem";

export type TvSeriesWatchProviders200ResultsAR = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsARFlatrateItem[];
};
