/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsBEFlatrateItem } from "./tvSeriesWatchProviders200ResultsBEFlatrateItem";

export type TvSeriesWatchProviders200ResultsBE = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsBEFlatrateItem[];
};
