/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsEGFlatrateItem } from "./tvSeasonWatchProviders200ResultsEGFlatrateItem";

export type TvSeasonWatchProviders200ResultsEG = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsEGFlatrateItem[];
};
