/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsPSFlatrateItem } from "./tvSeriesWatchProviders200ResultsPSFlatrateItem";

export type TvSeriesWatchProviders200ResultsPS = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsPSFlatrateItem[];
};
