/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsPHFlatrateItem } from "./tvSeriesWatchProviders200ResultsPHFlatrateItem";

export type TvSeriesWatchProviders200ResultsPH = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsPHFlatrateItem[];
};
