/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsPLFlatrateItem } from "./tvSeriesWatchProviders200ResultsPLFlatrateItem";
import type { TvSeriesWatchProviders200ResultsPLRentItem } from "./tvSeriesWatchProviders200ResultsPLRentItem";

export type TvSeriesWatchProviders200ResultsPL = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsPLFlatrateItem[];
  rent?: TvSeriesWatchProviders200ResultsPLRentItem[];
};
