/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsAGFlatrateItem } from "./tvSeasonWatchProviders200ResultsAGFlatrateItem";

export type TvSeasonWatchProviders200ResultsAG = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsAGFlatrateItem[];
};
