/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsTRFlatrateItem } from "./tvSeasonWatchProviders200ResultsTRFlatrateItem";

export type TvSeasonWatchProviders200ResultsTR = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsTRFlatrateItem[];
};
