/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsMCFlatrateItem } from "./tvSeasonWatchProviders200ResultsMCFlatrateItem";

export type TvSeasonWatchProviders200ResultsMC = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsMCFlatrateItem[];
};
