/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsIQFlatrateItem } from "./tvSeriesWatchProviders200ResultsIQFlatrateItem";

export type TvSeriesWatchProviders200ResultsIQ = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsIQFlatrateItem[];
};
