/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesAggregateCredits200CastItem } from "./tvSeriesAggregateCredits200CastItem";
import type { TvSeriesAggregateCredits200CrewItem } from "./tvSeriesAggregateCredits200CrewItem";

export type TvSeriesAggregateCredits200 = {
  cast?: TvSeriesAggregateCredits200CastItem[];
  crew?: TvSeriesAggregateCredits200CrewItem[];
  id?: number;
};
