/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeriesChangesParams = {
  end_date?: string;
  page?: number;
  start_date?: string;
};
