/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsBBFlatrateItem } from "./tvSeriesWatchProviders200ResultsBBFlatrateItem";

export type TvSeriesWatchProviders200ResultsBB = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsBBFlatrateItem[];
};
