/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsINFlatrateItem } from "./tvSeasonWatchProviders200ResultsINFlatrateItem";

export type TvSeasonWatchProviders200ResultsIN = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsINFlatrateItem[];
};
