/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsJMFlatrateItem } from "./tvSeriesWatchProviders200ResultsJMFlatrateItem";

export type TvSeriesWatchProviders200ResultsJM = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsJMFlatrateItem[];
};
