/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsPYFlatrateItem } from "./tvSeriesWatchProviders200ResultsPYFlatrateItem";

export type TvSeriesWatchProviders200ResultsPY = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsPYFlatrateItem[];
};
