/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsPTBuyItem } from "./tvSeasonWatchProviders200ResultsPTBuyItem";
import type { TvSeasonWatchProviders200ResultsPTFlatrateItem } from "./tvSeasonWatchProviders200ResultsPTFlatrateItem";

export type TvSeasonWatchProviders200ResultsPT = {
  link?: string;
  buy?: TvSeasonWatchProviders200ResultsPTBuyItem[];
  flatrate?: TvSeasonWatchProviders200ResultsPTFlatrateItem[];
};
