/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsSCFlatrateItem } from "./tvSeriesWatchProviders200ResultsSCFlatrateItem";

export type TvSeriesWatchProviders200ResultsSC = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsSCFlatrateItem[];
};
