/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsZWFlatrateItem } from "./tvSeasonWatchProviders200ResultsZWFlatrateItem";

export type TvSeasonWatchProviders200ResultsZW = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsZWFlatrateItem[];
};
