/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsGQFlatrateItem } from "./tvSeriesWatchProviders200ResultsGQFlatrateItem";

export type TvSeriesWatchProviders200ResultsGQ = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsGQFlatrateItem[];
};
