/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200Results } from "./tvSeriesWatchProviders200Results";

export type TvSeriesWatchProviders200 = {
  id?: number;
  results?: TvSeriesWatchProviders200Results;
};
