/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsDOFlatrateItem } from "./tvSeasonWatchProviders200ResultsDOFlatrateItem";

export type TvSeasonWatchProviders200ResultsDO = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsDOFlatrateItem[];
};
