/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsBSFlatrateItem } from "./tvSeriesWatchProviders200ResultsBSFlatrateItem";

export type TvSeriesWatchProviders200ResultsBS = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsBSFlatrateItem[];
};
