/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsPEFlatrateItem } from "./tvSeasonWatchProviders200ResultsPEFlatrateItem";

export type TvSeasonWatchProviders200ResultsPE = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsPEFlatrateItem[];
};
