/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesScreenedTheatrically200ResultsItem } from "./tvSeriesScreenedTheatrically200ResultsItem";

export type TvSeriesScreenedTheatrically200 = {
  id?: number;
  results?: TvSeriesScreenedTheatrically200ResultsItem[];
};
