/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsTZFlatrateItem } from "./tvSeriesWatchProviders200ResultsTZFlatrateItem";

export type TvSeriesWatchProviders200ResultsTZ = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsTZFlatrateItem[];
};
