/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsMDFlatrateItem } from "./tvSeriesWatchProviders200ResultsMDFlatrateItem";

export type TvSeriesWatchProviders200ResultsMD = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsMDFlatrateItem[];
};
