/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsFRBuyItem } from "./tvSeasonWatchProviders200ResultsFRBuyItem";
import type { TvSeasonWatchProviders200ResultsFRFlatrateItem } from "./tvSeasonWatchProviders200ResultsFRFlatrateItem";

export type TvSeasonWatchProviders200ResultsFR = {
  link?: string;
  buy?: TvSeasonWatchProviders200ResultsFRBuyItem[];
  flatrate?: TvSeasonWatchProviders200ResultsFRFlatrateItem[];
};
