/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsGYFlatrateItem } from "./tvSeasonWatchProviders200ResultsGYFlatrateItem";

export type TvSeasonWatchProviders200ResultsGY = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsGYFlatrateItem[];
};
