/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsHNFlatrateItem } from "./tvSeasonWatchProviders200ResultsHNFlatrateItem";

export type TvSeasonWatchProviders200ResultsHN = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsHNFlatrateItem[];
};
