/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesTranslations200TranslationsItem } from "./tvSeriesTranslations200TranslationsItem";

export type TvSeriesTranslations200 = {
  id?: number;
  translations?: TvSeriesTranslations200TranslationsItem[];
};
