/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeasonChangesById200ChangesItemItemsItemValue = {
  episode_id?: number;
  episode_number?: number;
};
