/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeasonImagesParams = {
  /**
   * specify a comma separated list of ISO-639-1 values to query, for example: `en-US,null`
   */
  include_image_language?: string;
  language?: string;
};
