/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsFIBuyItem } from "./tvSeriesWatchProviders200ResultsFIBuyItem";
import type { TvSeriesWatchProviders200ResultsFIFlatrateItem } from "./tvSeriesWatchProviders200ResultsFIFlatrateItem";

export type TvSeriesWatchProviders200ResultsFI = {
  link?: string;
  buy?: TvSeriesWatchProviders200ResultsFIBuyItem[];
  flatrate?: TvSeriesWatchProviders200ResultsFIFlatrateItem[];
};
