/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsMLFlatrateItem } from "./tvSeasonWatchProviders200ResultsMLFlatrateItem";

export type TvSeasonWatchProviders200ResultsML = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsMLFlatrateItem[];
};
