/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsRUAdsItem } from "./tvSeriesWatchProviders200ResultsRUAdsItem";
import type { TvSeriesWatchProviders200ResultsRUFlatrateItem } from "./tvSeriesWatchProviders200ResultsRUFlatrateItem";

export type TvSeriesWatchProviders200ResultsRU = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsRUFlatrateItem[];
  ads?: TvSeriesWatchProviders200ResultsRUAdsItem[];
};
