/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsTHFlatrateItem } from "./tvSeasonWatchProviders200ResultsTHFlatrateItem";

export type TvSeasonWatchProviders200ResultsTH = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsTHFlatrateItem[];
};
