/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsAEFlatrateItem } from "./tvSeasonWatchProviders200ResultsAEFlatrateItem";

export type TvSeasonWatchProviders200ResultsAE = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsAEFlatrateItem[];
};
