/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsMXFlatrateItem } from "./tvSeriesWatchProviders200ResultsMXFlatrateItem";

export type TvSeriesWatchProviders200ResultsMX = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsMXFlatrateItem[];
};
