/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsSAFlatrateItem } from "./tvSeasonWatchProviders200ResultsSAFlatrateItem";

export type TvSeasonWatchProviders200ResultsSA = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsSAFlatrateItem[];
};
