/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeriesLatestId200SeasonsItem = {
  air_date?: unknown;
  episode_count?: number;
  id?: number;
  name?: string;
  overview?: string;
  poster_path?: unknown;
  season_number?: number;
};
