/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeriesChanges200ChangesItemItemsItemValuePoster = {
  file_path?: string;
  iso_639_1?: string;
};
