/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesWatchProviders200ResultsHRFlatrateItem } from "./tvSeriesWatchProviders200ResultsHRFlatrateItem";

export type TvSeriesWatchProviders200ResultsHR = {
  link?: string;
  flatrate?: TvSeriesWatchProviders200ResultsHRFlatrateItem[];
};
