/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsMUFlatrateItem } from "./tvSeasonWatchProviders200ResultsMUFlatrateItem";

export type TvSeasonWatchProviders200ResultsMU = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsMUFlatrateItem[];
};
