/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsBZFlatrateItem } from "./tvSeasonWatchProviders200ResultsBZFlatrateItem";

export type TvSeasonWatchProviders200ResultsBZ = {
  link?: string;
  flatrate?: TvSeasonWatchProviders200ResultsBZFlatrateItem[];
};
