/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesChanges200ChangesItemItemsItem } from "./tvSeriesChanges200ChangesItemItemsItem";

export type TvSeriesChanges200ChangesItem = {
  key?: string;
  items?: TvSeriesChanges200ChangesItemItemsItem[];
};
