/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonChangesById200ChangesItemItemsItem } from "./tvSeasonChangesById200ChangesItemItemsItem";

export type TvSeasonChangesById200ChangesItem = {
  key?: string;
  items?: TvSeasonChangesById200ChangesItemItemsItem[];
};
