/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type TvSeriesAggregateCredits200CrewItemJobsItem = {
  credit_id?: string;
  job?: string;
  episode_count?: number;
};
