/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeasonWatchProviders200ResultsSEBuyItem } from "./tvSeasonWatchProviders200ResultsSEBuyItem";
import type { TvSeasonWatchProviders200ResultsSEFlatrateItem } from "./tvSeasonWatchProviders200ResultsSEFlatrateItem";

export type TvSeasonWatchProviders200ResultsSE = {
  link?: string;
  buy?: TvSeasonWatchProviders200ResultsSEBuyItem[];
  flatrate?: TvSeasonWatchProviders200ResultsSEFlatrateItem[];
};
