/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { TvSeriesContentRatings200ResultsItem } from "./tvSeriesContentRatings200ResultsItem";

export type TvSeriesContentRatings200 = {
  results?: TvSeriesContentRatings200ResultsItem[];
  id?: number;
};
