/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { WatchProviderTvList200ResultsItemDisplayPriorities } from "./watchProviderTvList200ResultsItemDisplayPriorities";

export type WatchProviderTvList200ResultsItem = {
  display_priorities?: WatchProviderTvList200ResultsItemDisplayPriorities;
  display_priority?: number;
  logo_path?: string;
  provider_name?: string;
  provider_id?: number;
};
