/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */

export type WatchProvidersAvailableRegions200ResultsItem = {
  iso_3166_1?: string;
  english_name?: string;
  native_name?: string;
};
