/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { WatchProvidersAvailableRegions200ResultsItem } from "./watchProvidersAvailableRegions200ResultsItem";

export type WatchProvidersAvailableRegions200 = {
  results?: WatchProvidersAvailableRegions200ResultsItem[];
};
