/**
 * Generated by orval v8.7.0 🍺
 * Do not edit manually.
 * tmdb-api
 * OpenAPI spec version: 3
 */
import type { WatchProviderTvList200ResultsItem } from "./watchProviderTvList200ResultsItem";

export type WatchProviderTvList200 = {
  results?: WatchProviderTvList200ResultsItem[];
};
